#JPA
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      use-new-id-generator-mappings: false
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  datasource:
    #### CMS_DB DataSource Configuration2
    cms-datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://storereview.ci48003jbapz.us-east-1.rds.amazonaws.com:3306/STOREREVIEW_DB
      username: admin
      password: review123

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'com-review-storereview-project-jwt-token-secret-key-com-review-storereview-project-jwt-token-secret-key'|base64
  secret: Y29tLXJldmlldy1zdG9yZXJldmlldy1wcm9qZWN0LWp3dC10b2tlbi1zZWNyZXQta2V5LWNvbS1yZXZpZXctc3RvcmVyZXZpZXctcHJvamVjdC1qd3QtdG9rZW4tc2VjcmV0LWtleQ==
  token-validity-in-seconds: 864000

#ReviewService를 SHA256암호화 후 앞에서 32Byte
aes-secret: 184EBFA87C052FB66887177B429201CE

logging:
  org:
    hibernate:
      SQL: debug
      type:
        descriptor:
          sql: trace
  level:
    root: info

# S3
cloud:
  aws:
    s3:
      bucket: storereview-bucket
    region:
      static: us-east-2
    stack:
      auto: false
    credentials:
      accessKey: AKIAYYPTKEMG6UANUHZZ
      secretKey: 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
